# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FCEBD8
background         #101216
cursor             #FCEBD8

active_tab_foreground     #101216
active_tab_background     #FCEBD8
inactive_tab_foreground   #FCEBD8
inactive_tab_background   #101216

active_border_color   #FCEBD8
inactive_border_color #101216
bell_border_color     #6C3751

color0      #383A3E
color1		#6C3751
color2		#72344C
color3		#4A4A6D
color4		#21608F
color5		#166798
color6		#B8956C
color7		#F2DBBF
color8		#A99986
color9		#90496B
color10		#984565
color11		#626392
color12		#2C81BE
color13		#1D89CB
color14		#F6C790
color15		#F2DBBF
